/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAuroxToken, IAuroxTokenInterface } from "../IAuroxToken";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_newAddress",
        type: "address",
      },
    ],
    name: "SetNewContractAllowance",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "allowanceAddress",
        type: "address",
      },
    ],
    name: "setAllowance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAuroxToken__factory {
  static readonly abi = _abi;
  static createInterface(): IAuroxTokenInterface {
    return new utils.Interface(_abi) as IAuroxTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAuroxToken {
    return new Contract(address, _abi, signerOrProvider) as IAuroxToken;
  }
}
