"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.TokenVesting__factory = exports.IAuroxToken__factory = exports.AuroxToken__factory = exports.ERC20Mintable__factory = exports.StakingMaster__factory = exports.IStakingMaster__factory = exports.RewardHelpers__factory = exports.Provider__factory = exports.IProvider__factory = exports.EpochHelpers__factory = exports.Migrations__factory = exports.Token__factory = exports.IERC20__factory = exports.IERC20Metadata__factory = exports.ERC20__factory = exports.Ownable__factory = void 0;
var Ownable__factory_1 = require("./factories/Ownable__factory");
__createBinding(exports, Ownable__factory_1, "Ownable__factory");
var ERC20__factory_1 = require("./factories/ERC20__factory");
__createBinding(exports, ERC20__factory_1, "ERC20__factory");
var IERC20Metadata__factory_1 = require("./factories/IERC20Metadata__factory");
__createBinding(exports, IERC20Metadata__factory_1, "IERC20Metadata__factory");
var IERC20__factory_1 = require("./factories/IERC20__factory");
__createBinding(exports, IERC20__factory_1, "IERC20__factory");
var Token__factory_1 = require("./factories/Token__factory");
__createBinding(exports, Token__factory_1, "Token__factory");
var Migrations__factory_1 = require("./factories/Migrations__factory");
__createBinding(exports, Migrations__factory_1, "Migrations__factory");
var EpochHelpers__factory_1 = require("./factories/EpochHelpers__factory");
__createBinding(exports, EpochHelpers__factory_1, "EpochHelpers__factory");
var IProvider__factory_1 = require("./factories/IProvider__factory");
__createBinding(exports, IProvider__factory_1, "IProvider__factory");
var Provider__factory_1 = require("./factories/Provider__factory");
__createBinding(exports, Provider__factory_1, "Provider__factory");
var RewardHelpers__factory_1 = require("./factories/RewardHelpers__factory");
__createBinding(exports, RewardHelpers__factory_1, "RewardHelpers__factory");
var IStakingMaster__factory_1 = require("./factories/IStakingMaster__factory");
__createBinding(exports, IStakingMaster__factory_1, "IStakingMaster__factory");
var StakingMaster__factory_1 = require("./factories/StakingMaster__factory");
__createBinding(exports, StakingMaster__factory_1, "StakingMaster__factory");
var ERC20Mintable__factory_1 = require("./factories/ERC20Mintable__factory");
__createBinding(exports, ERC20Mintable__factory_1, "ERC20Mintable__factory");
var AuroxToken__factory_1 = require("./factories/AuroxToken__factory");
__createBinding(exports, AuroxToken__factory_1, "AuroxToken__factory");
var IAuroxToken__factory_1 = require("./factories/IAuroxToken__factory");
__createBinding(exports, IAuroxToken__factory_1, "IAuroxToken__factory");
var TokenVesting__factory_1 = require("./factories/TokenVesting__factory");
__createBinding(exports, TokenVesting__factory_1, "TokenVesting__factory");
